name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Google Cloud SDK
        run: |
          echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Set GCP Project
        run: gcloud config set project cloudside-academy

      - name: Install kubectl
        run: |
          sudo apt-get install -y kubectl

      - name: Get GKE credentials
        run: |
         sudo gcloud container clusters get-credentials ga-gke-ss-46 --zone us-central1-c --project cloudside-academy

      - name: Deploy to GKE
        run: |
         sudo kubectl apply -f kubernetes/deployment.yaml
