name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Google Cloud SDK
        run: |
          # Remove existing Google Cloud SDK sources
          sudo rm -f /etc/apt/sources.list.d/google-cloud-sdk.list
          
          # Add new Google Cloud SDK source
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          
          # Download and add the GPG key
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
          
          # Update package list
          sudo apt-get update
          
          # Install necessary packages
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Set GCP Project
        run: gcloud config set project cloudside-academy

      - name: Install kubectl
        run: |
          sudo apt-get install -y kubectl

      - name: Get GKE credentials
        run: |
         sudo gcloud container clusters get-credentials ga-gke-ss-46 --zone us-central1-c --project cloudside-academy

      - name: Deploy to GKE
        run: |
         sudo kubectl apply -f deployment.yaml
