name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.0
      with:
        version: 'latest'

    - name: Authenticate with Google Cloud
      run: echo "${{ secrets.GCP_KEY }}" | gcloud auth activate-service-account --key-file=-
    
    - name: Set GCP Project
      run: gcloud config set project cloudside-academy

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials ga-gke-ss-46 --zone us-central1-c --project cloudside-academy

    - name: Deploy to GKE
      run: |
        kubectl apply -f kubernetes/deployment.yaml
